import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';
import '@/css/globals.css';
import css from './layout.module.css';
import clsx from 'clsx';
import Header from '@/features/ui/header/Header/Header';
import Footer from '@/features/ui/Footer/Footer';

const plexSans = IBM_Plex_Sans({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--ibm-plex-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(plexSans.variable, css.app)}>
        <Header />

        <main className={css.main}>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
